name: Build and release jar with maven

on:
  push:
    tags:
      - '*' # Only if the commit has a tag

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file tool/pom.xml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "tool/target/mig-t*.jar"
